import { test, expect, type Page, type Locator } from '@playwright/test'

const canvas = (page: Page) => page.getByTestId('optics-canvas')
const component = (page: Page, kind: string) => page.locator(`[data-optics-kind="${kind}"]`).first()
async function worldPoint(page: Page, x: number, y: number) {
  return canvas(page).evaluate((svg: SVGSVGElement, point) => {
    const result = new DOMPoint(point.x, point.y).matrixTransform(svg.getScreenCTM()!)
    return { x: result.x, y: result.y }
  }, { x, y })
}
async function activate(locator: Locator, mobile: boolean) { if (mobile) await locator.tap(); else await locator.click() }
async function properties(page: Page, mobile: boolean, open: boolean) {
  if (mobile) await page.getByRole('button', { name: `${open ? '打开' : '关闭'}光学属性面板`, exact: true }).click()
}
async function rayGeometry(page: Page) {
  return page.getByTestId('optics-ray').evaluateAll(lines => lines.map(line => ['x1', 'y1', 'x2', 'y2'].map(key => line.getAttribute(key)).join(',')).join(';'))
}
async function scene(page: Page) {
  return page.evaluate(() => JSON.parse(localStorage.getItem('optics-lab.draft.v1') || 'null'))
}
async function drag(page: Page, mobile: boolean, from: { x: number; y: number }, to: { x: number; y: number }, cancel = false) {
  if (mobile) {
    const client = await page.context().newCDPSession(page)
    await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...from, id: 1 }] })
    for (let step = 1; step <= 8; step++) await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: from.x + (to.x - from.x) * step / 8, y: from.y + (to.y - from.y) * step / 8, id: 1 }] })
    if (cancel) await page.keyboard.press('Escape')
    await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await client.detach()
  } else {
    await page.mouse.move(from.x, from.y); await page.mouse.down()
    await page.mouse.move(to.x, to.y, { steps: 8 })
    if (cancel) await page.keyboard.press('Escape')
    await page.mouse.up()
  }
}

test.beforeEach(async ({ page }) => {
  // Playwright supplies a new browser context for every case; reloads in a case retain its draft.
  await page.goto('./#optics')
  await expect(canvas(page)).toBeVisible()
  await expect(page.getByTestId('optics-component-count')).toHaveText('3 个组件')
})

test('default image and focal input change the optical result without overflowing the viewport', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await expect.poll(() => page.getByTestId('optics-ray').count()).toBeGreaterThan(3)
  const originalRays = await rayGeometry(page)
  await activate(component(page, 'convex-lens'), mobile)
  await properties(page, mobile, true)
  const readout = page.getByTestId('optics-image-measurement')
  await expect(readout).toContainText('倒立缩小实像')
  await expect(readout.locator('dd').nth(1)).toContainText('20')
  const focus = page.getByRole('spinbutton', { name: '焦距', exact: true })
  await focus.fill('15'); await focus.blur()
  await expect(readout).toContainText('倒立等大实像')
  await expect(readout.locator('dd').nth(1)).toContainText('30')
  await expect.poll(() => rayGeometry(page)).not.toBe(originalRays)
  await focus.fill('12'); await focus.blur()
  await properties(page, mobile, false)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const bounds = await canvas(page).boundingBox()
  expect(bounds!.height).toBeGreaterThan(300)
  await page.screenshot({ path: `artifacts/optics-${testInfo.project.name}.png`, fullPage: true })
  expect(errors).toEqual([])
})

test('zoomed dragging is a single undoable edit, Escape restores it, and zoom and pan work', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  await page.getByRole('button', { name: '放大画布', exact: true }).click()
  const startView = await canvas(page).getAttribute('viewBox')
  const original = await component(page, 'convex-lens').getAttribute('transform')
  const from = await worldPoint(page, 50, 34), to = await worldPoint(page, 56, 37)
  await drag(page, mobile, from, to)
  await expect(component(page, 'convex-lens')).toHaveAttribute('transform', 'translate(56 37) rotate(0)')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(component(page, 'convex-lens')).toHaveAttribute('transform', original!)
  await expect(page.getByRole('button', { name: '撤销', exact: true })).toBeDisabled()
  await drag(page, mobile, from, to, true)
  await expect(component(page, 'convex-lens')).toHaveAttribute('transform', original!)
  await expect(page.getByRole('button', { name: '撤销', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '平移', exact: true }).click()
  const panStart = await worldPoint(page, 45, 45)
  await drag(page, mobile, panStart, { x: panStart.x + 35, y: panStart.y + 30 })
  await expect(canvas(page)).not.toHaveAttribute('viewBox', startView!)
  await expect(component(page, 'convex-lens')).toHaveAttribute('transform', original!)
  await page.getByRole('button', { name: '适应全部组件', exact: true }).click()
  await expect(component(page, 'object')).toBeVisible()
  await expect(component(page, 'screen')).toBeVisible()
})

test('component placement supports library panels, editing shortcuts, and multiple experiment presets', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  if (mobile) await page.getByRole('button', { name: '打开光学元件库', exact: true }).click()
  await activate(page.getByTestId('optics-palette-aperture'), mobile)
  await expect(page.locator('.optics-placement-hint')).toContainText('光阑')
  const point = await worldPoint(page, 60, 47)
  if (mobile) await page.touchscreen.tap(point.x, point.y); else await page.mouse.click(point.x, point.y)
  await expect(page.getByTestId('optics-component-count')).toHaveText('4 个组件')
  await expect(component(page, 'aperture')).toHaveAttribute('transform', 'translate(60 47) rotate(0)')
  await expect(page.locator('.optics-placement-hint')).toHaveCount(0)
  await canvas(page).focus(); await page.keyboard.press('r')
  await expect(component(page, 'aperture')).toHaveAttribute('transform', 'translate(60 47) rotate(15)')
  await page.keyboard.press('Control+z')
  await expect(component(page, 'aperture')).toHaveAttribute('transform', 'translate(60 47) rotate(0)')
  await page.keyboard.press('Delete')
  await expect(page.getByTestId('optics-component-count')).toHaveText('3 个组件')
  if (!mobile) {
    const dropPoint = await worldPoint(page, 35, 15), bounds = (await canvas(page).boundingBox())!
    await page.getByTestId('optics-palette-point-source').dragTo(canvas(page), { targetPosition: { x: dropPoint.x - bounds.x, y: dropPoint.y - bounds.y } })
    await expect(component(page, 'point-source')).toHaveAttribute('transform', 'translate(35 15) rotate(0)')
    await expect(page.getByTestId('optics-component-count')).toHaveText('4 个组件')
  }
  const presets = page.getByLabel('载入光学示例', { exact: true })
  await presets.selectOption('concave')
  await expect(component(page, 'concave-lens')).toBeVisible()
  await expect(page.locator('[data-testid="optics-ray"][data-virtual="true"]').first()).toBeVisible()
  await presets.selectOption('virtual')
  await properties(page, mobile, true)
  await expect(page.getByTestId('optics-image-measurement')).toContainText('正立放大虚像')
  await properties(page, mobile, false)
  for (const [preset, kind] of [['mirror', 'plane-mirror'], ['slab', 'glass-slab'], ['prism', 'prism']] as const) {
    await presets.selectOption(preset)
    await expect(component(page, kind)).toBeVisible()
    await expect.poll(() => page.getByTestId('optics-ray').count()).toBeGreaterThan(5)
  }
})

test('laser placement emits one ray and supports wavelength, direction, and reflection presets', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  await page.getByRole('button', { name: '新建空白光学实验', exact: true }).click()
  if (mobile) await page.getByRole('button', { name: '打开光学元件库', exact: true }).click()
  await expect(page.locator('.optics-palette .count-badge')).toHaveText('13')
  await expect(page.locator('.optics-palette .palette-footer')).toContainText('13 种')
  await activate(page.getByTestId('optics-palette-laser'), mobile)
  await expect(page.locator('.optics-placement-hint')).toContainText('激光笔')
  const point = await worldPoint(page, 40, 34)
  if (mobile) await page.touchscreen.tap(point.x, point.y); else await page.mouse.click(point.x, point.y)
  await expect(component(page, 'laser')).toBeVisible()
  await expect(page.getByTestId('optics-component-count')).toHaveText('1 个组件')
  await expect(page.getByTestId('optics-ray')).toHaveCount(1)
  const ray = page.getByTestId('optics-ray')
  await expect(ray).toHaveAttribute('x1', '40')
  await expect(ray).toHaveAttribute('y1', '34')
  await expect(ray).toHaveAttribute('y2', '34')
  await properties(page, mobile, true)
  await expect(page.getByRole('spinbutton', { name: '波长', exact: true })).toHaveValue('650')
  await expect(page.getByRole('spinbutton', { name: '光线数量', exact: true })).toHaveCount(0)
  await expect(page.getByRole('spinbutton', { name: '组件高度', exact: true })).toHaveCount(0)
  await expect(page.getByRole('spinbutton', { name: '发散角', exact: true })).toHaveCount(0)
  await expect(page.locator('.optics-properties')).toContainText('从笔尖发射一条光线')
  const red = await ray.getAttribute('stroke')
  const wavelength = page.getByRole('spinbutton', { name: '波长', exact: true })
  await wavelength.fill('532'); await wavelength.blur()
  await expect(ray).not.toHaveAttribute('stroke', red!)
  const angle = page.getByRole('spinbutton', { name: '旋转角', exact: true })
  await angle.fill('30'); await angle.blur()
  await expect(component(page, 'laser')).toHaveAttribute('transform', 'translate(40 34) rotate(30)')
  const direction = await ray.evaluate(line => ({ dx: Number(line.getAttribute('x2')) - Number(line.getAttribute('x1')), dy: Number(line.getAttribute('y2')) - Number(line.getAttribute('y1')) }))
  expect(direction.dx).toBeGreaterThan(0)
  expect(direction.dy / direction.dx).toBeCloseTo(Math.tan(Math.PI / 6), 5)
  expect((await scene(page)).components[0]).toMatchObject({ kind: 'laser', wavelength: 532, angle: 30, rayCount: 1, spread: 0 })
  await page.getByTestId('optics-orientation-vertical').click()
  await expect(page.getByTestId('optics-orientation-vertical')).toHaveAttribute('aria-pressed', 'true')
  await expect(component(page, 'laser')).toHaveAttribute('transform', 'translate(40 34) rotate(90)')
  await page.getByTestId('optics-orientation-horizontal').click()
  await expect(page.getByTestId('optics-orientation-horizontal')).toHaveAttribute('aria-pressed', 'true')
  await expect(component(page, 'laser')).toHaveAttribute('transform', 'translate(40 34) rotate(0)')
  await angle.fill('30'); await angle.blur()
  await properties(page, mobile, false)
  await page.reload()
  await expect(component(page, 'laser')).toHaveAttribute('transform', 'translate(40 34) rotate(30)')
  await page.getByLabel('载入光学示例', { exact: true }).selectOption('laser')
  await expect(component(page, 'laser')).toBeVisible()
  await expect(component(page, 'plane-mirror')).toBeVisible()
  await expect(component(page, 'screen')).toBeVisible()
  const reflectedRays = page.locator('[data-testid="optics-ray"]:not([data-virtual="true"])')
  await expect(reflectedRays).toHaveCount(2)
  const lastRay = reflectedRays.last()
  expect(Number(await lastRay.getAttribute('x2'))).toBeCloseTo(43, 5)
  expect(Number(await lastRay.getAttribute('y2'))).toBeCloseTo(34 + 12 * Math.sqrt(3), 5)
})

test('microscope is composed of independent lenses with intermediate and final images', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  if (mobile) await page.getByRole('button', { name: '打开光学元件库', exact: true }).click()
  await expect(page.locator('.optics-palette .count-badge')).toHaveText('13')
  await expect(page.getByTestId('optics-palette-microscope')).toHaveCount(0)
  await expect(page.getByTestId('optics-palette-telescope')).toHaveCount(0)
  if (mobile) await page.getByRole('button', { name: '关闭光学元件库', exact: true }).click()
  await page.getByLabel('载入光学示例', { exact: true }).selectOption('microscope')
  const lenses = page.locator('[data-optics-kind="convex-lens"]')
  const objective = lenses.nth(0), eyepiece = lenses.nth(1)
  await expect(lenses).toHaveCount(2)
  await expect(page.getByTestId('optics-component-count')).toHaveText('3 个组件')
  await expect(objective).toContainText('物镜')
  await expect(eyepiece).toContainText('目镜')
  await expect(page.getByTestId('optics-image')).toHaveCount(2)
  await expect(canvas(page).getByText('中间实像', { exact: true })).toBeVisible()
  await expect(canvas(page).getByText('最终虚像', { exact: true })).toBeVisible()
  const finalImage = page.locator('[data-testid="optics-image"][data-image-nature="virtual"]')
  expect(Number(await finalImage.getAttribute('data-image-x'))).toBeCloseTo(-2.5, 4)
  expect(Number(await finalImage.getAttribute('data-image-y'))).toBeCloseTo(58, 4)
  const traced = await page.getByTestId('optics-ray').evaluateAll(lines => lines.map(line => ({
    x1: Number(line.getAttribute('x1')), y1: Number(line.getAttribute('y1')),
    x2: Number(line.getAttribute('x2')), y2: Number(line.getAttribute('y2')),
    virtual: line.getAttribute('data-virtual') === 'true',
  })))
  const betweenLenses = traced.filter(ray => !ray.virtual && Math.abs(ray.x1 - 25.5) < 1e-3 && Math.abs(ray.x2 - 45.5) < 1e-3)
  expect(betweenLenses).toHaveLength(3)
  for (const ray of betweenLenses) {
    const intermediateY = ray.y1 + (40.1666666667 - ray.x1) * (ray.y2 - ray.y1) / (ray.x2 - ray.x1)
    expect(intermediateY).toBeCloseTo(36.6666666667, 3)
  }
  const outgoing = traced.filter(ray => !ray.virtual && Math.abs(ray.x1 - 45.5) < 1e-3)
  expect(outgoing).toHaveLength(3)
  for (const ray of outgoing) {
    const extendedY = ray.y1 + (-2.5 - ray.x1) * (ray.y2 - ray.y1) / (ray.x2 - ray.x1)
    expect(extendedY).toBeCloseTo(58, 3)
  }
  expect(traced.filter(ray => ray.virtual && Math.abs(ray.x2 + 2.5) < 1e-3 && Math.abs(ray.y2 - 58) < 1e-3)).toHaveLength(3)
  await page.screenshot({ path: 'artifacts/optics-microscope-' + testInfo.project.name + '.png', fullPage: true })

  const initialGeometry = await rayGeometry(page)
  await activate(objective, mobile)
  await properties(page, mobile, true)
  const focus = page.getByRole('spinbutton', { name: '焦距', exact: true })
  await expect(focus).toHaveValue('4')
  await expect(page.getByTestId('optics-image-measurement').last()).toContainText('累计放大率 m')
  await expect(page.getByTestId('optics-image-measurement').last().locator('dd').last()).toHaveText('-24')
  await focus.fill('3.5'); await focus.blur()
  await expect.poll(() => rayGeometry(page)).not.toBe(initialGeometry)
  expect((await scene(page)).components.filter((c: { kind: string }) => c.kind === 'convex-lens').map((c: { focalLength: number }) => c.focalLength)).toEqual([3.5, 6])
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(focus).toHaveValue('4')
  await properties(page, mobile, false)
  await activate(eyepiece, mobile)
  await properties(page, mobile, true)
  await expect(focus).toHaveValue('6')
  await focus.fill('7'); await focus.blur()
  expect((await scene(page)).components.filter((c: { kind: string }) => c.kind === 'convex-lens').map((c: { focalLength: number }) => c.focalLength)).toEqual([4, 7])
  await properties(page, mobile, false)

  await page.getByRole('button', { name: '切换网格吸附', exact: true }).click()
  const objectiveTransform = await objective.getAttribute('transform')
  const beforeMove = await rayGeometry(page)
  await drag(page, mobile, await worldPoint(page, 45.5, 34), await worldPoint(page, 44.5, 34))
  await expect(eyepiece).toHaveAttribute('transform', 'translate(44.5 34) rotate(0)')
  await expect(objective).toHaveAttribute('transform', objectiveTransform!)
  await expect.poll(() => rayGeometry(page)).not.toBe(beforeMove)
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(eyepiece).toHaveAttribute('transform', 'translate(45.5 34) rotate(0)')
  await page.getByRole('button', { name: '重做', exact: true }).click()
  const saved = await scene(page)
  await page.reload()
  await expect(lenses).toHaveCount(2)
  expect(await scene(page)).toEqual(saved)
  await expect(eyepiece).toHaveAttribute('transform', 'translate(44.5 34) rotate(0)')
  await expect(canvas(page).getByText('最终虚像', { exact: true })).toBeVisible()
})

test('telescope uses two convex lenses with parallel emerging rays', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  await page.getByLabel('载入光学示例', { exact: true }).selectOption('telescope')
  const lenses = page.locator('[data-optics-kind="convex-lens"]')
  await expect(lenses).toHaveCount(2)
  await expect(component(page, 'parallel-source')).toBeVisible()
  await expect(page.getByTestId('optics-component-count')).toHaveText('3 个组件')
  const rays = await page.locator('[data-testid="optics-ray"]:not([data-virtual="true"])').evaluateAll(lines => lines.map(line => ({
    x1: Number(line.getAttribute('x1')), y1: Number(line.getAttribute('y1')),
    x2: Number(line.getAttribute('x2')), y2: Number(line.getAttribute('y2')),
  })))
  const focused = rays.filter(ray => Math.abs(ray.x1 - 39) < 1e-3 && Math.abs(ray.x2 - 71) < 1e-3)
  expect(focused).toHaveLength(7)
  for (const ray of focused) {
    expect(ray.y1 + (63 - ray.x1) * (ray.y2 - ray.y1) / (ray.x2 - ray.x1)).toBeCloseTo(34, 4)
  }
  const emerging = rays.filter(ray => Math.abs(ray.x1 - 71) < 1e-3)
  expect(emerging).toHaveLength(7)
  for (const ray of emerging) expect(ray.y2).toBeCloseTo(ray.y1, 4)
  await page.screenshot({ path: 'artifacts/optics-telescope-' + testInfo.project.name + '.png', fullPage: true })
  await activate(lenses.nth(1), mobile)
  await properties(page, mobile, true)
  await expect(page.getByRole('spinbutton', { name: '焦距', exact: true })).toHaveValue('8')
  const distance = page.getByRole('spinbutton', { name: 'X 坐标', exact: true })
  const initialGeometry = await rayGeometry(page)
  await distance.fill('69'); await distance.blur()
  await expect(lenses.nth(0)).toHaveAttribute('transform', 'translate(39 34) rotate(0)')
  await expect.poll(() => rayGeometry(page)).not.toBe(initialGeometry)
})

test('pause freezes the traced geometry while edits persist and resume updates the rays', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  const original = await rayGeometry(page)
  await page.getByRole('button', { name: '暂停仿真', exact: true }).click()
  await activate(component(page, 'convex-lens'), mobile)
  await properties(page, mobile, true)
  const focus = page.getByRole('spinbutton', { name: '焦距', exact: true })
  await focus.fill('18'); await focus.blur()
  expect(await rayGeometry(page)).toBe(original)
  await expect.poll(async () => (await scene(page)).components.find((c: { kind: string }) => c.kind === 'convex-lens').focalLength).toBe(18)
  await properties(page, mobile, false)
  await page.getByRole('button', { name: '运行仿真', exact: true }).click()
  await expect.poll(() => rayGeometry(page)).not.toBe(original)
  await expect(page.locator('.optics-canvas-notice')).toHaveCount(0)
})

test('total internal reflection is traced and reported on the canvas', async ({ page }) => {
  await page.getByLabel('载入光学示例', { exact: true }).selectOption('slab')
  const draft = await scene(page)
  const source = draft.components.find((c: { kind: string }) => c.kind === 'parallel-source')
  Object.assign(source, { x: 50, y: 34, angle: 60, rayCount: 1 })
  await page.getByLabel('导入光学工程文件', { exact: true }).setInputFiles({ name: 'internal-reflection.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(draft)) })
  await expect(page.locator('.optics-canvas-warning')).toContainText('发生全反射')
  await expect.poll(() => page.getByTestId('optics-ray').count()).toBeGreaterThan(2)
  const geometry = await rayGeometry(page)
  expect(geometry).not.toMatch(/NaN|Infinity/)
})

test('curved mirrors expose focal controls, matching circular surfaces and an opaque back', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  for (const kind of ['concave-mirror', 'convex-mirror']) {
    await page.getByLabel('载入光学示例', { exact: true }).selectOption(kind)
    const mirror = component(page, kind)
    await expect(mirror.locator('.optics-mirror-surface')).toHaveAttribute('d', /A24 24/)
    await expect(page.getByTestId('optics-image-measurement')).toContainText('近轴估计')
    await activate(mirror, mobile)
    await properties(page, mobile, true)
    const focus = page.getByRole('spinbutton', { name: '近轴焦距', exact: true })
    await focus.fill('18'); await focus.blur()
    await expect(mirror.locator('.optics-mirror-surface')).toHaveAttribute('d', /A36 36/)
    await expect(page.getByTestId('optics-foci').locator('g').first()).toHaveAttribute('transform', `translate(${kind === 'concave-mirror' ? -18 : 18} 0)`)
    await page.screenshot({ path: `artifacts/optics-${kind}-${testInfo.project.name}.png`, fullPage: true })
    await page.getByRole('button', { name: '翻转反射面', exact: true }).click()
    await properties(page, mobile, false)
    await expect(page.locator('.optics-canvas-warning')).toContainText('背面阻挡')
    await expect(page.getByTestId('optics-image')).toHaveCount(0)
  }
})

test('invalid imports preserve the scene, JSON round trips and drafts remain independent of electricity', async ({ page }, testInfo) => {
  const mobile = testInfo.project.name === 'mobile'
  await page.getByLabel('载入光学示例', { exact: true }).selectOption('slab')
  const saved = await scene(page)
  await page.getByLabel('导入光学工程文件', { exact: true }).setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{"kind":"optics-lab","components":[]}') })
  await expect(page.getByRole('alert')).toContainText('无法导入')
  expect(await scene(page)).toEqual(saved)
  await expect(component(page, 'glass-slab')).toBeVisible()
  await page.getByRole('button', { name: '关闭错误提示', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出光学 JSON', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^optics-.*\.json$/)
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []; for await (const chunk of stream!) chunks.push(chunk)
  const exported = Buffer.concat(chunks)
  expect(JSON.parse(exported.toString())).toEqual(saved)
  await page.getByRole('button', { name: '新建空白光学实验', exact: true }).click()
  await expect(page.getByTestId('optics-component-count')).toHaveText('0 个组件')
  await page.getByLabel('导入光学工程文件', { exact: true }).setInputFiles({ name: 'optics.json', mimeType: 'application/json', buffer: exported })
  await expect(component(page, 'glass-slab')).toBeVisible()
  await page.reload()
  await expect(component(page, 'glass-slab')).toBeVisible()
  expect(await scene(page)).toEqual(saved)
  await page.goto('./#circuit')
  await expect(page.locator('.react-flow')).toBeVisible()
  await expect(page.getByTestId('component-count')).toHaveText('0 个元件')
  if (mobile) await page.getByRole('button', { name: '打开元件库', exact: true }).click()
  await page.getByTestId('palette-battery').click()
  await page.locator('.react-flow__pane').click({ position: { x: 120, y: 150 } })
  await expect(page.getByTestId('component-count')).toHaveText('1 个元件')
  await page.goto('./#optics')
  await expect(component(page, 'glass-slab')).toBeVisible()
  expect(await scene(page)).toEqual(saved)
  await page.reload()
  await expect(component(page, 'glass-slab')).toBeVisible()
  await page.goto('./#circuit')
  await expect(page.getByTestId('component-count')).toHaveText('1 个元件')
  await page.goBack()
  await expect(component(page, 'glass-slab')).toBeVisible()
  await page.goForward()
  await expect(page.getByTestId('component-count')).toHaveText('1 个元件')
})
