import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { join, relative } from 'node:path'

const root = fileURLToPath(new URL('../', import.meta.url))
const folder = join(root, 'prompts')
const output = join(root, 'server/promptCatalog.generated.ts')
const manifest = JSON.parse(await readFile(join(folder, 'manifest.json'), 'utf8'))
if (manifest.schemaVersion !== 1 || typeof manifest.version !== 'string') throw new Error('Invalid prompt manifest')
const texts = {}, metadata = {}, discovered = []
async function visit(directory) {
  for (const file of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
    const path = join(directory, file.name)
    if (file.isSymbolicLink()) throw new Error(`Prompt symlinks are unsupported: ${path}`)
    if (file.isDirectory()) await visit(path)
    else if (file.name.endsWith('.md') && path !== join(folder, 'README.md')) discovered.push(path)
  }
}
await visit(folder)
for (const path of discovered) {
  const id = relative(folder, path).replaceAll('\\', '/').replace(/\.md$/, '')
  const entry = manifest.prompts[id]
  if (!entry) throw new Error(`Prompt missing from manifest: ${id}`)
  const content = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(await readFile(path))
  if (!content.trim() || content.includes('\u0000') || content.startsWith('\uFEFF')) throw new Error(`Invalid UTF-8 prompt: ${id}`)
  const variables = [...new Set([...content.matchAll(/\{\{([A-Za-z][A-Za-z0-9_]*)\}\}/g)].map(match => match[1]))].sort()
  if (JSON.stringify(variables) !== JSON.stringify([...(entry.variables || [])].sort())) throw new Error(`Prompt variables differ from manifest: ${id}`)
  texts[id] = content
  metadata[id] = { version: entry.version || manifest.version, sha256: createHash('sha256').update(content).digest('hex'), variables }
}
for (const id of Object.keys(manifest.prompts)) if (!(id in texts)) throw new Error(`Prompt file missing: ${id}`)
const result = '// Generated by scripts/generate-prompts.mjs. Edit prompts/**/*.md instead.\n'
  + `export const PROMPT_TEXTS: Readonly<Record<string, string>> = Object.freeze(${JSON.stringify(texts, null, 2)})\n`
  + `export const PROMPT_METADATA = Object.freeze(Object.fromEntries(Object.entries(${JSON.stringify(metadata, null, 2)}).map(([id, entry]) => [id, Object.freeze({ ...entry, variables: Object.freeze(entry.variables) })])))\n`
const existing = await readFile(output, 'utf8').catch(() => '')
if (process.argv.includes('--check')) {
  if (result !== existing) throw new Error('Prompt catalog is stale. Run npm run prompts:generate.')
} else if (result !== existing) await writeFile(output, result)
process.stdout.write(`Validated ${discovered.length} prompt files${process.argv.includes('--check') ? ' (catalog up to date)' : ''}.\n`)
